export const levels = [
  { title: 'Primaire', color: '#FF4136' },
  { title: 'Collège', color: '#FF851B' },
  { title: 'Lycée', color: '#3D9970' },
]

export function getFormattedDate(date) {
  return `${date.getDate()}/${date.getMonth() + 1}/${date.getFullYear()}`
}

const patterns = {
  fullname: /^([a-z]{3,12})(\s)([a-z]{3,12})?(\s)?([a-z]{3,12})?$/i,
  level: /[a-z]/i,
  birthday:
    /(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[13-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{2})/,
  phone: /^0(\d\d)(\d\d)(\d\d)(\d\d)(\d)$/,
}

export function isValid(string, field) {
  return patterns[field].test(string)
}

export const COLORS = {
  white: '#fff',
  black: '#000',
  blue: '#5D5FEE',
  lightblue: '#87CEEB',
  grey: '#BABBC3',
  light: '#F3F4FB',
  darkBlue: '#7978B5',
  red: 'red',
}

export const dropDownLevels = [
  { label: 'Primaire', value: 'pri' },
  { label: '6ème année', value: '6P', parent: 'pri' },
  { label: '5ème année', value: '5P', parent: 'pri' },
  { label: '4ème année', value: '4P', parent: 'pri' },
  { label: '3ème année', value: '3P', parent: 'pri' },
  { label: '2ème année', value: '2P', parent: 'pri' },
  { label: '1ère année', value: '1P', parent: 'pri' },

  { label: 'Collège', value: 'na' },
  { label: '3AC', value: '3AC', parent: 'na' },
  { label: '2AC', value: '2AC', parent: 'na' },
  { label: '1AC', value: '1AC', parent: 'na' },

  { label: 'Lycée', value: 'ly' },
  { label: 'TC', value: 'TSC', parent: 'ly' },
  { label: '1BAC', value: '1BAC', parent: 'ly' },
  { label: '2BAC', value: '2BAC', parent: 'ly' },
]

export const months = [
  'Septembre',
  'Octobre',
  'Novembre',
  'Décembre',
  'Janvier',
  'Février',
  'Mars',
  'Avril',
  'Mai',
  'Juin',
]

export const dummyAdherents = [
  {
    birthday: '09/10/16',
    fullname: 'Rachid Amrani Alaoui',
    id: 'cbc53663-d73b-4af5-b06b-956b747d27cf',
    level: '3P',
    paiment: {
      Avril: false,
      Décembre: false,
      Février: false,
      Janvier: false,
      Juin: false,
      Mai: false,
      Mars: false,
      Novembre: false,
      Octobre: false,
      Septembre: true,
    },
    phone: '0665552412',
    registrationDate: '09/21/22',
    responsible: 'Mère',
  },
  {
    birthday: '09/09/06',
    fullname: 'Amine Mohamed',
    id: 'a389ff8d-5a5d-4887-a0e8-c4adefb31840',
    level: '1BAC',
    paiment: {
      Avril: false,
      Décembre: false,
      Février: false,
      Janvier: true,
      Juin: true,
      Mai: false,
      Mars: false,
      Novembre: false,
      Octobre: false,
      Septembre: false,
    },
    phone: '0652324175',
    registrationDate: '09/21/22',
    responsible: 'Mère',
  },
  {
    birthday: '09/21/01',
    fullname: 'Hakim Jamal',
    id: 'ed1fdf66-44e6-4e86-9879-6bd66dfe8a8e',
    level: 'TSC',
    paiment: {
      Avril: false,
      Décembre: false,
      Février: false,
      Janvier: false,
      Juin: false,
      Mai: false,
      Mars: false,
      Novembre: false,
      Octobre: false,
      Septembre: false,
    },
    phone: '0652266339',
    registrationDate: '09/21/22',
    responsible: 'Père',
  },
  {
    birthday: '09/11/04',
    fullname: 'Hafsa Alaoui',
    id: 'd0ebb58f-6131-4b85-be3e-62a9aea66f89',
    level: '2AC',
    paiment: {
      Avril: false,
      Décembre: false,
      Février: false,
      Janvier: false,
      Juin: false,
      Mai: false,
      Mars: false,
      Novembre: false,
      Octobre: false,
      Septembre: false,
    },
    phone: '0566885544',
    registrationDate: '09/21/22',
    responsible: 'Père',
  },
  {
    birthday: '09/21/13',
    fullname: 'Abdellah Amraoui',
    id: '593bf88f-8ea3-4e84-a3e2-dfdd531baf84',
    level: '1AC',
    paiment: {
      Avril: false,
      Décembre: false,
      Février: false,
      Janvier: false,
      Juin: false,
      Mai: false,
      Mars: false,
      Novembre: false,
      Octobre: false,
      Septembre: false,
    },
    phone: '0688556633',
    registrationDate: '09/21/22',
    responsible: 'Autre',
  },
  {
    birthday: '09/08/11',
    fullname: 'Ibrahim Alla',
    id: 'aef0998a-c2ad-419b-bd22-621024dcb75b',
    level: '2AC',
    paiment: {
      Avril: false,
      Décembre: false,
      Février: false,
      Janvier: false,
      Juin: false,
      Mai: false,
      Mars: false,
      Novembre: false,
      Octobre: false,
      Septembre: false,
    },
    phone: '0655663355',
    registrationDate: '09/21/22',
    responsible: 'Père',
  },
  {
    birthday: '06/16/16',
    fullname: 'Soukayna Jamal',
    id: '177c6295-c418-4c8e-932c-44fbd576402f',
    level: '3AC',
    paiment: {
      Avril: false,
      Décembre: false,
      Février: true,
      Janvier: false,
      Juin: false,
      Mai: false,
      Mars: false,
      Novembre: false,
      Octobre: true,
      Septembre: false,
    },
    phone: '0655336688',
    registrationDate: '09/21/22',
    responsible: 'Mère',
  },
  {
    birthday: '09/21/13',
    fullname: 'Othmane Abdou',
    id: '09368066-ba9c-42c8-bcbe-8cb859a98956',
    level: '4P',
    paiment: {
      Avril: false,
      Décembre: false,
      Février: false,
      Janvier: false,
      Juin: false,
      Mai: false,
      Mars: false,
      Novembre: false,
      Octobre: false,
      Septembre: false,
    },
    phone: '0685237614',
    registrationDate: '09/21/22',
    responsible: 'Père',
  },
  {
    birthday: '09/21/04',
    fullname: 'Anas Mrabti',
    id: '45dce803-1fa6-4a24-a726-c45f182b93d4',
    level: '2BAC',
    paiment: {
      Avril: false,
      Décembre: false,
      Février: false,
      Janvier: false,
      Juin: false,
      Mai: false,
      Mars: false,
      Novembre: false,
      Octobre: true,
      Septembre: true,
    },
    phone: '0655663322',
    registrationDate: '09/21/22',
    responsible: 'Père',
  },
]
